### ISSUE TITLE
Feature : Add Default Landing Page

### ISSUE THREAD

**Issue by abhinavk454** [myretro/ProjectLRLD#8]
**After closing this issue site must have a landing _Home_ _Page_**
> **_Items checklist_**

- [x] **Heading**
- [x] **Title**
- [x] **Welcome Message**
- [x] **Sign In** 
- [x] **Register**
- [x] **Nav Ba**

**Comment by abhinavk454** [comment]
```bash
DB_URI="mongodb+srv://lazarus:2441139@dhar-chai.fg0kz.mongodb.net/lrld"
PORT=5000
```

**Comment by myretro** [comment]
Added picture as welcome
