### ISSUE TITLE
Feature : Add a Register View

### ISSUE THREAD

**Issue by abhinavk454** [myretro/ProjectLRLD#9]
**After closing this issue site must have a landing _Register_ _Page_**
> **_Form contains following checklist items_**

- [ ] **Full Name**
- [ ] **Email**
- [ ] **Password**
- [ ] **Confirm Password** 
- [ ] **Message**

**Comment by abhinavk454** [comment]
`git fetch origin`
`git checkout 9-feature-add-a-register-view`

**Comment by myretro** [comment]
http://woshub.com/install-windows-subsystem-android-run-apps/
